image: python:3.12-slim


stages:
  - lint

lint:
  stage: lint
  before_script:
    - apt update && apt install git -y
    - pip install uv
    - uv pip install -r pyproject.toml --extra dev --system
  script:
    - pre-commit run --all-files
  except:
    refs:
      - tags
