image: python:3.12-slim


stages:
  - lint

lint:
  stage: lint
  before_script:
    - apt update && apt install git -y
    - pip install uv
    - uv sync --frozen --extra dev
  script:
    - pre-commit run --all-files
  except:
    refs:
      - tags
