repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0  # Use the latest stable revision
    hooks:
      # Ensures that every file ends with a single newline character
      - id: end-of-file-fixer
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff-format
        language: system
        entry: ruff format
        types_or: [ python, jupyter ]
      - id: ruff-check
        name: ruff-check
        language: system
        entry: ruff check
        types_or: [ python, jupyter ]
