[project]
name = "gridnet"
version = "0.1.0"
authors = [
  { name="Yan Zhang", email="dev.claude.yan.zhang@gmail.com" },
]
description = "A python library to create simple power grid and calculate powerflow."
readme = "README.md"
keywords = ["python", "power system", "power grid", "powerflow", "machine learning"]
license = { file="LICENSE" }
requires-python = ">=3.11"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries"
]

dependencies = [
    "pandas",
    "numpy",
    "polars",
    "pyarrow",
    "scikit-learn",
    "torch",
]

[project.optional-dependencies]
dev = ["pre-commit", "ruff"]
doc = [
    "wheel",
    "mkdocs-material",
    "mknotebooks",
    "matplotlib",
    "notebook",
]
test = [
    "pytest",
    "pytest-cov"
]

[project.urls]
"Homepage" = "https://github.com/claudezss/gridnet"
"Bug Tracker" = "https://gitlab.com/claudezss/gridnet/-/issues"


[tool.hatch.build.targets.wheel]
packages = ["src/gridnet"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
